import { StyleSheet } from "react-native";
import { hp, wp } from "../constants/device";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  //main container
  mainContainer: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  container: {
    paddingTop: hp(5),
    backgroundColor: colors.bg,
  },

  headerLogo: {
    height: hp(8),
    width: wp(70),
    marginLeft: wp(3),
  },

  contentContainer: {
    flex: 1,
    backgroundColor: colors.bg,
  },

  requestModalBackground: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.transparent,
  },
  requestModalContainer: {
    backgroundColor: colors.bg,
    padding: hp(2),
    height: hp(50),
    width: wp(80),
    borderRadius: hp(4),
    alignItems: "center",
  },
  requestModalIcon: {
    fontSize: hp(10),
    color: colors.main,
    marginTop: hp(3),
    marginBottom: hp(5),
  },
  requestModalTitle: {
    fontSize: hp(3),
    color: colors.text,
    marginBottom: hp(1),
  },
  requestModalTitle2: {
    fontSize: hp(2),
    color: colors.text,
    marginBottom: hp(10),
    textAlign: "center",
  },
  requestModalButtonContainer: {
    flexDirection: "row",
  },
  requestModalButton: {
    width: wp(30),
    height: hp(4),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.main,
    borderRadius: hp(3),
    marginRight: wp(5),
  },
  requestModalButtonText: {
    fontSize: hp(2),
    color: colors.bg,
  },
  requestModalButton2: {
    width: wp(30),
    height: hp(4),
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.bg,
    borderRadius: hp(3),
    borderWidth: 1,
    borderColor: colors.main,
    marginLeft: wp(5),
  },
  requestModalButtonText2: {
    fontSize: hp(2),
    color: colors.main,
  },

  selectSedeModalContainer: {
    backgroundColor: colors.bg,
    padding: hp(2),
    height: hp(50),
    width: wp(80),
    borderRadius: hp(4),
    alignItems: "center",
  },
  closeSedeModalIconContainer: {
    alignSelf: "flex-end",
  },
  closeSedeModalIcon: {
    fontSize: hp(3),
    color: colors.red,
  },
  selectSedeModalTitle: {
    textAlign: "center",
    fontSize: hp(4),
    color: colors.text,
  },
  selectSedeModalSedeButton: {
    width: wp(40),
    height: hp(5),
    marginTop: hp(2),
    borderWidth: 1,
    borderColor: colors.main,
    borderRadius: hp(3),
    justifyContent: "center",
    alignItems: "center",
  },
  selectSedeModalSedeButtonSelected: {
    width: wp(40),
    height: hp(5),
    marginTop: hp(2),
    backgroundColor: colors.main,
    borderRadius: hp(3),
    justifyContent: "center",
    alignItems: "center",
  },
  selectSedeModalSedeButtonText: {
    fontSize: hp(2),
    color: colors.main,
  },
  selectSedeModalSedeButtonTextSelected: {
    fontSize: hp(2),
    color: colors.bg,
  },

  map: {
    ...StyleSheet.absoluteFillObject,
  },

  arrowUpIcon: {
    position: "absolute",
    zIndex: 1,
    color: colors.main,
    fontSize: hp(3),
    right: wp(10.3),
    bottom: hp(34.5),
  },
  arrowDownIcon: {
    position: "absolute",
    zIndex: 1,
    color: colors.main,
    fontSize: hp(3),
    right: wp(10.3),
    bottom: hp(15.3),
  },

  openParkingLotContainer: {
    width: wp(20),
    height: hp(19),
    position: "absolute",
    right: wp(2),
    bottom: hp(17),
  },
  openParkingLotRed: {
    width: wp(10),
    height: hp(5),
    backgroundColor: colors.red,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: hp(2),
    borderRadius: hp(1.5),
  },
  openParkingLotYellow: {
    width: wp(10),
    height: hp(5),
    backgroundColor: colors.yellow,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: hp(2),
    borderRadius: hp(1.5),
  },
  openParkingLotGreen: {
    width: wp(10),
    height: hp(5),
    backgroundColor: colors.green,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: hp(2),
    borderRadius: hp(1.5),
  },
  openParkingLotText: {
    fontSize: hp(1.3),
    color: colors.bg,
  },

  selectSedeButton: {
    position: "absolute",
    right: wp(2),
    bottom: hp(11),
    width: wp(20),
    height: hp(3),
    borderRadius: hp(3),
    borderWidth: 1,
    borderColor: colors.main,
    justifyContent: "center",
    alignItems: "center",
  },
  selectSedeButtonText: {
    fontSize: hp(2),
    color: colors.main,
  },

  modalBackground: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: colors.transparent,
  },
  modalContainer: {
    backgroundColor: colors.bg,
    padding: hp(2),
    height: hp(60),
    width: wp(100),
    borderTopLeftRadius: hp(4),
    borderTopRightRadius: hp(4),
    position: "relative",
  },
  modalTitleContainer: {
    flexDirection: "row",
    marginTop: hp(1),
    marginBottom: hp(2),
  },
  modalTitle1: {
    fontSize: hp(3),
    color: colors.text,
  },
  modalTitle2: {
    fontSize: hp(3),
    color: colors.accent,
  },
  modalRedIcon: {
    fontSize: hp(7),
    color: colors.red,
    position: "absolute",
    right: wp(3),
    top: hp(1),
  },
  modalYellowIcon: {
    fontSize: hp(7),
    color: colors.yellow,
    position: "absolute",
    right: wp(3),
    top: hp(1),
  },
  modalGreenIcon: {
    fontSize: hp(7),
    color: colors.green,
    position: "absolute",
    right: wp(3),
    top: hp(1),
  },
  modalTextContainer: {
    flexDirection: "row",
  },
  modalText: {
    fontSize: hp(2.2),
    color: colors.text,
    marginTop: hp(2),
  },
  modalModifyTitle: {
    fontSize: hp(3),
    color: colors.text,
    fontWeight: "bold",
    marginBottom: hp(1),
    marginTop: hp(7),
    alignSelf: "center",
  },
  modalModifyIconsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: wp(15),
  },
  modalModifyIcon: {
    fontSize: hp(7),
    color: colors.grey,
  },
  modalModifyIconSelected: {
    fontSize: hp(7),
    color: colors.main,
  },
  modalModifyNumber: {
    borderWidth: 1,
    borderColor: colors.main,
    borderRadius: hp(3),
    width: wp(20),
    height: hp(10),
    justifyContent: "center",
    alignItems: "center",
  },
  modalModifyNumberTextRed: {
    fontSize: hp(4),
    color: colors.red,
  },
  modalModifyNumberTextYellow: {
    fontSize: hp(4),
    color: colors.yellow,
  },
  modalModifyNumberTextGreen: {
    fontSize: hp(4),
    color: colors.green,
  },
  modalCapacityMessageRed: {
    fontSize: hp(4),
    color: colors.red,
    marginTop: hp(5),
    textAlign: "center",
  },
  modalCapacityMessageYellow: {
    fontSize: hp(4),
    color: colors.yellow,
    marginTop: hp(5),
    textAlign: "center",
  },
  modalCapacityMessageGreen: {
    fontSize: hp(4),
    color: colors.green,
    marginTop: hp(5),
    textAlign: "center",
  },
  modalCloseButton: {
    height: hp(7),
    width: wp(80),
    borderRadius: hp(3),
    backgroundColor: colors.main,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    marginTop: hp(8),
  },
  modalCloseButtonText: {
    fontSize: hp(2),
    color: colors.bg,
  },

  navbarContainer2: {
    backgroundColor: colors.bg,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: wp(10),
    borderTopLeftRadius: hp(4),
    borderTopRightRadius: hp(4),
    height: hp(10),
    position: "absolute",
    bottom: 0,
    width: wp(100),
  },
  navbarContainer: {
    backgroundColor: colors.bg,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: wp(10),
    borderTopLeftRadius: hp(4),
    borderTopRightRadius: hp(4),
    height: hp(10),
    position: "absolute",
    bottom: 0,
    width: wp(100),
  },
  navbarIcon: {
    fontSize: hp(5),
    color: colors.main,
  },

  feedbackContainer: {
    position: "absolute",
    top: hp(30),
    left: wp(15),
    backgroundColor: colors.main,
    borderRadius: hp(3),
    height: hp(40),
    width: wp(70),
    paddingHorizontal: wp(2),
    justifyContent: "center",
  },
  feedbackText: {
    fontSize: hp(3),
    fontWeight: "bold",
    color: colors.bg,
    textAlign: "center",
    paddingBottom: 30,
  },
  feedBackClose: {
    fontSize: hp(3),
    fontWeight: "bold",
    color: colors.red,
    textAlign: "center",
  },
});
